from tools import generate_image, upscale_image, review_image
import os
from dotenv import load_dotenv
from autogen import ConversableAgent
from autogen import register_function
from autogen import GroupChat, GroupChatManager

load_dotenv()

# create agent
image_generator = ConversableAgent(
    name="image_generator",
    system_message = """
    You are a world class AI image prompt engineer, you will be given an image of a cloth, and text prompt (either original prompt or the iterated prompt from image reviwer )
    with the info given, you will use generate_image to generate a realistic photo of a person wearing specific cloth.

    You will continously iterate image based on feedback from image_reviewer, until the image_reviewer is satisfied with the image.
    """,
    llm_config={
        "config_list": [
            {
                "model": "gpt-4o",
                "api_key": os.environ["OPENAI_API_KEY"]
            }
        ],
        "timeout": 120
    }
)

image_reviewer = ConversableAgent(
    name="image_reviewer",
    system_message = """
    You are a world class AI image reviewer, you will review both original_cloth_image as well as image generated by the image_generator based on image urls,
    classify if the cloth in image from image_generator is 98% match with the original cloth image.
    If more than 98% match, just return "98% match", if not 98% match, if less than 98% match, list out the discrepancies, and generate an iterated text prompt for image_generator to generate a new image.
    with the info given, you will use review_image to review the image and provide feedback to image_generator.

    You will continously review image based on feedback from image_generator, until you are satisfied with the image.
    """,
    llm_config={
        "config_list": [
            {
                "model": "gpt-4o",
                "api_key": os.environ["OPENAI_API_KEY"]
            }
        ],
        "timeout": 120
    },
    is_termination_msg=lambda msg: "98% match" in msg["content"].lower()
)

image_finetuner = ConversableAgent(
    name="image_finetuner",
    system_message = """
    turn the final image generated and approved by image_generator and image_reviewer into a high quality image and upscale the final image.
    After image upscaled, return "TERMINATE" to end the conversation.
    """,
    llm_config={
        "config_list": [
            {
                "model": "gpt-4o",
                "api_key": os.environ["OPENAI_API_KEY"]
            }
        ],
        "timeout": 120
    },
    is_termination_msg=lambda msg: "terminate" in msg["content"].lower()
)

user_proxy = ConversableAgent(
    name="User",
    llm_config={
        "config_list": [
            {
                "model": "gpt-4o",
                "api_key": os.environ["OPENAI_API_KEY"]
            }
        ],
        "timeout": 120
    },
    is_termination_msg=lambda msg: msg.get("content") is not None and "TERMINATE" in msg["content"].upper(),
    human_input_mode="NEVER"
)

# # register functions
register_function(
    generate_image,
    caller=image_generator,
    executor=user_proxy,
    name="generate_image",
    description="generate image with AI model based on original cloth image and text prompt"
)

# image_generator.register_for_llm(
#     name="generate_image",
#     description="generate image with AI model based on original cloth image and text prompt"
# )

# user_proxy.register_for_execution(name="generate_image")(generate_image)

register_function(
    review_image,
    caller=image_reviewer,
    executor=user_proxy,
    name="review_image",
    description="compare and review images"
)

# image_reviewer.register_for_llm(
#     name="review_image",
#     description="compare and review images"
# )

# user_proxy.register_for_execution(name="review_image")(review_image)

register_function(
    upscale_image,
    caller=image_finetuner,
    executor=user_proxy,
    name="upscale_image",
    description="upscale image to make it high quality"
)

# image_finetuner.register_for_llm(
#     name="upscale_image",
#     description="upscale image to make it high quality"
# )

# user_proxy.register_for_execution(name="upscale_image")(upscale_image)

group_chat = GroupChat(
    agents = [image_generator, image_reviewer, user_proxy],
    messages= [],
    max_round=13
)

group_chat_manager = GroupChatManager(
    groupchat=group_chat,
    llm_config={
        "config_list": [
            {
                "model": "gpt-4o",
                "api_key": os.environ["OPENAI_API_KEY"]
            }
        ]
    }
)

cloth_image = "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSxdgOidgNFBLQRZ91bdbC-2d3JFMnP7GZ4HAo4BqpE1cTeaz39Q8BI81L0mbTBwYRycz2Xy1g_q7RgXygFn3Le54q0p1zLRnJ265gcSogByzaxGwL3BFhBx2Y"
base_prompt = "woman wearing blue sweater, full image with white background"

chat_result = user_proxy.initiate_chats(
    [
        {
            "recipient": group_chat_manager,
            "message": f"""
            *original_cloth_image* {cloth_image}
            *base_prompt* {base_prompt}
            ---------------------------------------------------------------
            Generate a realistic photo based on the original cloth image and base prompt above that pass 100% match from image_reviewer.
            """,
            "summary_method": "reflection_with_llm",
            "summary_args": {
                "summary_prompt": "Including the latest latest_ai_image_url, as well as original_cloth_image and latest prompt"
            }
        },
    ]
)